name: CI/CD SplitterMR

on:
  push:
    branches: [cache-test]

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # Cache ONLY the first stage of test image
      - name: Prime cache (test deps)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.test
          target: deps                 # ← build only deps stage
          load: false
          provenance: false
          cache-from: type=gha,scope=splitter_mr_deps
          cache-to:   type=gha,mode=max,scope=splitter_mr_deps
          build-args: |
            BUILDKIT_PROGRESS=plain

      # Cache ONLY the first stage of docs image
      - name: Prime cache (docs deps)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.docs
          target: deps
          load: false
          provenance: false
          cache-from: type=gha,scope=splitter_mr_deps
          cache-to:   type=gha,mode=max,scope=splitter_mr_deps
          build-args: |
            BUILDKIT_PROGRESS=plain

  test_check:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build full test image (reuse deps cache; don’t upload heavy layers)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.test
          tags: splitter_mr_tests:latest
          load: true
          provenance: false
          cache-from: type=gha,scope=splitter_mr_deps
          build-args: |
            EXTRAS=[markitdown,docling]
            BUILDKIT_PROGRESS=plain

      - name: Run tests
        run: docker run --rm splitter_mr_tests:latest

  publish_docs:
    runs-on: ubuntu-latest
    needs: test_check
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build docs image (reuse deps cache; don’t upload heavy layers)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.docs
          tags: splitter_mr_docs:latest
          load: true
          provenance: false
          cache-from: type=gha,scope=splitter_mr_deps
          # no cache-to here → heavy layers aren’t saved
          build-args: |
            EXTRAS=
            BUILDKIT_PROGRESS=plain

      - name: Deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -v "${{ github.workspace }}/.git:/app/.git" \
            splitter_mr_docs:latest
