name: CI/CD SplitterMR

on:
  push:
    branches: [cache-test]

permissions:
  contents: write

jobs:
  check_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build test image (no cache)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.test
          tags: splitter_mr_tests:latest
          load: true
          provenance: false
          no-cache: true
          build-args: |
            EXTRAS=[markitdown,docling]

      - name: Run tests (coverage gate inside image)
        run: docker run --rm splitter_mr_tests:latest

  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build docs image (no cache)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.docs
          tags: splitter_mr_docs:latest
          load: true
          provenance: false
          no-cache: true
          build-args: |
            EXTRAS=

      - name: Deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -v "${{ github.workspace }}/.git:/app/.git" \
            splitter_mr_docs:latest