name: CI/CD SplitterMR

on:
  push:
    branches:
      - cache-test

permissions:
  contents: write

jobs:
  test_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build docker image for testing (cached)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.test
          tags: splitter_mr_tests:latest
          load: true
          provenance: false          # needed when load: true
          cache-from: type=gha,scope=splitter_mr_tests
          cache-to: type=gha,mode=max,scope=splitter_mr_tests
          build-args: |
            BUILDKIT_PROGRESS=plain  # clearer logs to confirm cache hits

      - name: Run tests and check coverage
        run: docker run --rm splitter_mr_tests:latest

  publish_docs:
    runs-on: ubuntu-latest
    needs: test_check
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build docker for Docs (cached)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.docs
          tags: splitter_mr_docs:latest
          load: true
          provenance: false
          cache-from: type=gha,scope=splitter_mr_docs
          cache-to: type=gha,mode=max,scope=splitter_mr_docs
          build-args: |
            BUILDKIT_PROGRESS=plain

      - name: Deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker run --rm -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} splitter_mr_docs:latest